FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit requests \
    && mkdir -p /app/data \
    && chmod 777 /app/data

COPY src /app/src
ENV PYTHONPATH=/app/src

CMD ["streamlit", "run", "src/mvp_rag/ui_chat.py", "--server.address=0.0.0.0"]
